### ISSUE TITLE
work ?

### ISSUE THREAD

**Issue by Feromon32** [A5R13L/gmsv_apakr_plugin#1]
Get error after start server, altnugh did everitning as it is you vritten yn the readme:

 failed to dlopen /home/server87919/game/garrysmod/lua/bin/gmsv_apakr_plugin.so error=/home/server87919/game/garrysmod/lua/bin/gmsv_apakr_plugin.so: undefined symbol: curl_mime_addpart, version CURL_OPENSSL_4
(Unable to load plugin "lua/bin/gmsv_apakr_plugin.so")

**Comment by A5R13L** [comment]
What host are you using? As well as what linux distro & version?

**Comment by Feromon32** [comment]
I use MyArena hosting, I’m not sure about the distro here, but  is most likely Ubuntu 16.04 LTS

I also tested on my local Ubuntu 22.04.5 LTS machine, but there was no such error there, I only got a notification message 
(Unable to load plugin “lua/bin/gmsv_apakr_plugin.so”)

**Comment by A5R13L** [comment]
What does running `curl --version` on your local machine output?

**Comment by Feromon32** [comment]
curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18
Release-Date: 2022-01-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets zstd

**Comment by A5R13L** [comment]
It should work on your local machine then, if it just says "Unable to load plugin", something is preventing it from loading. You might need to try and use gdb to see if it throws anything when it fails to load.

As for the hosting error, they're using a version of curl that is too old, they would need to update it for it to work.

**Comment by A5R13L** [comment]
You can try using ldd to see if things are missing for it on your local machine as well.

**Comment by Feromon32** [comment]
ok, thx, i try it

**Comment by A5R13L** [comment]
If it all fails, I'd recommend using Wisp/Pterodactyl/Pelican to host it, as that is what most hosts use and it seems to work on them just fine.

**Comment by A5R13L** [comment]
Assuming it's been resolved.
