### ISSUE TITLE
How to compile for Windows?

### ISSUE THREAD

**Issue by SMorganYu** [A5R13L/gmsv_apakr_plugin#4]
Hi! I'm having trouble with building x64 windows apakr. It compiles but doesn't starts in srcds. And plugin weight only 2.7 MB
![image](https://github.com/user-attachments/assets/40e4d65f-e441-4724-9603-6dd632a421c2)

**Comment by SMorganYu** [comment]
And I tried to name .so to .dll as the instructions. srcds deduces an error that it is incompatible with windows

**Comment by A5R13L** [comment]
It is not compatible with windows to any extent, and the releases are not compatible either. Windows has multiple issues, that I do not have the time to figure out. If you want to try it yourself, you will need to set it up to build for windows and statically link the dependencies.

**Comment by A5R13L** [comment]
On 64 bit windows, IServer is either wrong signature, or the vtable is different as `GetClient` causes an access violation.

On 32 bit windows, it should work with no problems.

**Comment by A5R13L** [comment]
So I budged and messed with it again, I've got windows 64 bit working now properly. I will push a release for the builds shortly.
